version: "3.9"

services:
  front:
    image: horsesmart-web-front
    container_name: horsesmart-web-front
    build: .
    ports:
      - 3000:3000
    networks:
      - horsesmart


networks:
  horsesmart:
    name: horsesmart
