export const API_URL = process.env.NEXT_PUBLIC_API_URL
export const IMAGES_URL = process.env.NEXT_PUBLIC_IMAGES_URL
export const ADMIN_URL = process.env.NEXT_PUBLIC_ADMIN_URL
export const DOWNLOAD_IOS_APP_LINK = process.env.NEXT_PUBLIC_DOWNLOAD_IOS_APP_LINK
export const DOWNLOAD_ANDROID_APP_LINK = process.env.NEXT_PUBLIC_DOWNLOAD_ANDROID_APP_LINK
export const SUPPORT_LINK = process.env.NEXT_PUBLIC_SUPPORT_LINK
export const PRIVACY_POLICY_LINK = process.env.NEXT_PUBLIC_PRIVACY_POLICY_LINK